### ISSUE TITLE
Program crashes when changing material selection

### ISSUE THREAD

**Issue by Claw76** [Pangamma/PixelStacker#14]
title says everything. the zipped report file contains nothing. It crashes at the "compiling color map based on material list" step when pressing render, or when exiting the material selection window

Edit:
It works perfectly fine if I disable the "enable 2nd layer" option

**Comment by Pangamma** [comment]
I will take a look into it today and see if I can come up with a fix. Thank you for your bug report. Quick question which operating system are you using for this?

**Comment by Claw76** [comment]
I'm using Windows 10

**Comment by Pangamma** [comment]
@Claw76  Can you try again with the latest release?
https://github.com/Pangamma/PixelStacker/releases/download/1.16.5b/Release.zip

**Comment by Claw76** [comment]
Ok, now it did produce a proper crash report
[pixelstacker-error-report.zip](https://github.com/Pangamma/PixelStacker/files/5945582/pixelstacker-error-report.zip)

**Comment by Claw76** [comment]
I think I get it now, why it crashes. I'm removing the glass which it needs to make the 2nd layer and therefore, it crashes.

**Comment by Pangamma** [comment]
These error reports are actually super useful. Basically if no glass is selected, even though multi layer is enabled, it will set a variable to zero. PixelStacker then later divides by that number causing the exception. I'll add in a fix so that if no "layer 2" type materials are selected it will just revert to using single layer style.

**Comment by Pangamma** [comment]
I think the latest build fixes it.
